const contractsReport = {
  handlerData: resJSON => {
    const templateSource = document.getElementById('template').innerHTML;
    const handlebarTemplate = Handlebars.compile(templateSource);
    const contractsTableHtml = handlebarTemplate(resJSON);
    document.getElementById('root').innerHTML = contractsTableHtml;
  }
};

window.onload = function() {
  const jsonData = {
    accounts: [
      {
        accountName: '202 AGVENTURES',
        commodities: [
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '152.0',
                    date: '2020-10-16 09:02:48.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1914596',
                    currentAdjPrice: '299.46',
                    futures: '0.0',
                    basis: '299.46',
                    deferPayDate: '2020-10-16 09:02:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: 'merch contracts'
                  }
                ],
                cropYear: '2020-2021',
                x: null,
                prodcontracts: [
                  {
                    quantityToBeDelivered: '152.0',
                    date: '2020-10-16 09:02:48.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1914596',
                    currentAdjPrice: '299.46',
                    futures: '0.0',
                    basis: '299.46',
                    deferPayDate: '2020-10-16 09:02:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: 'prod contracts'
                  }
                ],
                gpoContracts: [
                  {
                    quantityToBeDelivered: '152.0',
                    date: '2020-10-16 09:02:48.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1914596',
                    currentAdjPrice: '299.46',
                    futures: '0.0',
                    basis: '299.46',
                    deferPayDate: '2020-10-16 09:02:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: 'gpo contracts'
                  }
                ]
              },
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '152.0',
                    date: '2020-10-16 09:02:48.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1914596',
                    currentAdjPrice: '299.46',
                    futures: '0.0',
                    basis: '299.46',
                    deferPayDate: '2020-10-16 09:02:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: 'merch contracts'
                  }
                ],
                gpoContracts: [
                  {
                    quantityToBeDelivered: '152.0',
                    date: '2020-10-16 09:02:48.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1914596',
                    currentAdjPrice: '299.46',
                    futures: '0.0',
                    basis: '299.46',
                    deferPayDate: '2020-10-16 09:02:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: 'gpo contracts'
                  }
                ],
                cropYear: '2021-2022',
                x: null,
                prodcontracts: null
              },
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '152.0',
                    date: '2020-10-16 09:02:48.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1914596',
                    currentAdjPrice: '299.46',
                    futures: '0.0',
                    basis: '299.46',
                    deferPayDate: '2020-10-16 09:02:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2022-2023',
                x: null,
                prodcontracts: null
              }
            ],
            commodityName: 'AMBER DURUM'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '226.0',
                    date: '2020-08-11 17:37:10.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1902907',
                    currentAdjPrice: '493.8',
                    futures: '493.8',
                    basis: null,
                    deferPayDate: '2020-08-11 17:37:10.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '226.0',
                    date: '2020-08-11 17:38:22.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1902908',
                    currentAdjPrice: '493.8',
                    futures: '493.8',
                    basis: null,
                    deferPayDate: '2020-08-11 17:38:22.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '226.0',
                    date: '2020-08-11 17:39:33.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1902910',
                    currentAdjPrice: '493.8',
                    futures: '493.8',
                    basis: null,
                    deferPayDate: '2020-08-11 17:39:33.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-08-11 17:37:10.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: '',
                    contractNumber: '1902907',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-08-11 17:37:10.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-08-11 17:38:22.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: '',
                    contractNumber: '1902908',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-08-11 17:38:22.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-08-11 17:39:33.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: '',
                    contractNumber: '1902910',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-08-11 17:39:33.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-05-21 09:22:41.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1890710',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-05-21 09:22:41.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '1225.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '350.0',
                    date: '2020-07-09 14:15:55.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1897987',
                    currentAdjPrice: '495.0',
                    futures: '495.0',
                    basis: null,
                    deferPayDate: '2020-07-09 14:15:55.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '500.0',
                    date: '2020-07-20 13:24:29.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1899587',
                    currentAdjPrice: '499.0',
                    futures: '499.0',
                    basis: null,
                    deferPayDate: '2020-07-20 13:24:29.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '350.0',
                    date: '2020-05-21 09:22:41.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1890710',
                    currentAdjPrice: '488.08',
                    futures: '488.08',
                    basis: null,
                    deferPayDate: '2020-05-21 09:22:41.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '500.0',
                    date: '2020-09-09 17:08:36.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1907488',
                    currentAdjPrice: '499.0',
                    futures: '499.0',
                    basis: null,
                    deferPayDate: '2020-09-09 17:08:36.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '1000.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '453.5',
                    date: '2020-09-17 14:12:16.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1909130',
                    currentAdjPrice: '-26.0',
                    futures: null,
                    basis: '-26.0',
                    deferPayDate: '2020-09-17 14:12:16.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-07-09 14:15:55.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: '',
                    contractNumber: '1897987',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-07-09 14:15:55.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-05-21 09:22:41.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: '',
                    contractNumber: '1890710',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-05-21 09:22:41.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-09-09 17:08:36.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: '',
                    contractNumber: '1907488',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-09-09 17:08:36.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '500.0',
                    date: '2020-07-21 17:45:30.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1899965',
                    currentAdjPrice: '462.96999999999997',
                    futures: '491.7',
                    basis: '-28.73',
                    deferPayDate: '2020-07-21 17:45:30.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '500.0',
                    date: '2020-09-22 15:10:35.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1910310',
                    currentAdjPrice: '462.96999999999997',
                    futures: '491.7',
                    basis: '-28.73',
                    deferPayDate: '2020-09-22 15:10:35.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '1000.0',
                    currentValue: '-'
                  }
                ],
                cropYear: '2019-2020',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CANOLA'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '254.08',
                    date: '2020-07-10 18:18:18.0',
                    deliveryPoint: '191-PREM Marquis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1898492',
                    currentAdjPrice: '520.8',
                    futures: '494.8',
                    basis: '26.0',
                    deferPayDate: '2020-07-10 18:18:18.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '36.36',
                    date: '2020-07-21 14:15:37.0',
                    deliveryPoint: '191-PREM Marquis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1899851',
                    currentAdjPrice: '479.2',
                    futures: '487.2',
                    basis: '-8.0',
                    deferPayDate: '2020-07-21 14:15:37.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2019-08-22 15:55:04.0',
                    deliveryPoint: '191-PREM Marquis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1852946',
                    currentAdjPrice: '480.0',
                    futures: '480.0',
                    basis: null,
                    deferPayDate: '2019-08-22 15:55:04.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '1088.6',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '217.72',
                    date: '2019-08-22 15:55:04.0',
                    deliveryPoint: '191-PREM Marquis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1852946',
                    currentAdjPrice: '477.0',
                    futures: '480.0',
                    basis: '-3.0',
                    deferPayDate: '2019-08-22 15:55:04.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CSCO CANOLA'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '1500.0',
                    date: '2020-03-20 12:40:18.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1881840',
                    currentAdjPrice: '54.38',
                    futures: null,
                    basis: '54.38',
                    deferPayDate: '2020-03-20 12:40:18.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '1000.0',
                    date: '2020-10-02 09:28:24.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1912060',
                    currentAdjPrice: '258.02',
                    futures: '204.76',
                    basis: '53.26',
                    deferPayDate: '2020-10-02 09:28:24.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '73.0',
                    date: '2020-10-05 10:37:03.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1912492',
                    currentAdjPrice: '257.21',
                    futures: '206.23',
                    basis: '50.98',
                    deferPayDate: '2020-10-05 10:37:03.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '1000.0',
                    date: '2020-03-20 09:23:48.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1881273',
                    currentAdjPrice: '256.13',
                    futures: '207.97',
                    basis: '48.16',
                    deferPayDate: '2020-03-20 09:23:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-04-20 17:44:53.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1886752',
                    currentAdjPrice: '21.08',
                    futures: null,
                    basis: '21.08',
                    deferPayDate: '2020-04-20 17:44:53.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '460.0',
                    date: '2020-04-20 17:44:53.0',
                    deliveryPoint: 'Moose Jaw SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1886752',
                    currentAdjPrice: '216.64999999999998',
                    futures: '195.57',
                    basis: '21.08',
                    deferPayDate: '2020-04-20 17:44:53.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'RED SPRING WHEAT'
          }
        ],
        accountNumber: '1249893'
      },
      {
        accountName: 'MDM Aqua Farms Ltd',
        commodities: [
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '258.0',
                    date: '2020-09-22 11:28:18.0',
                    deliveryPoint: 'AB G12 Big Valley O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1910141',
                    currentAdjPrice: '509.36000000000007',
                    futures: '521.7',
                    basis: '-12.34',
                    deferPayDate: '2020-09-22 11:28:18.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CRUSH CANOLA'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '6.05',
                    date: '2020-06-29 16:28:44.0',
                    deliveryPoint: 'AB G12 PREMBig Valley O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1896343',
                    currentAdjPrice: '502.7',
                    futures: '484.7',
                    basis: '18.0',
                    deferPayDate: '2020-06-29 16:28:44.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '218.35',
                    date: '2020-06-29 16:25:53.0',
                    deliveryPoint: 'AB G12 PREMBig Valley O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1896342',
                    currentAdjPrice: '483.6',
                    futures: '479.6',
                    basis: '4.0',
                    deferPayDate: '2020-06-29 16:25:53.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CSCO CANOLA'
          }
        ],
        accountNumber: '1192706'
      },
      {
        accountName: 'Willowmarsh Dairy Farms Ltd',
        commodities: [
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-03 08:19:28.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1875107',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-03 08:19:28.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '560.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '80.0',
                    date: '2020-02-03 08:19:28.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1875107',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-03 08:19:28.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '80.0',
                    date: '2019-11-26 11:30:42.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1865910',
                    currentAdjPrice: '500.52000000000004',
                    futures: '498.8',
                    basis: '1.72',
                    deferPayDate: '2019-11-26 11:30:42.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '560.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '55.428',
                    date: '2020-01-31 08:42:18.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1874995',
                    currentAdjPrice: '460.32000000000005',
                    futures: '459.6',
                    basis: '0.72',
                    deferPayDate: '2020-01-31 08:42:18.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CANOLA'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '150.0',
                    date: '2020-03-19 13:17:25.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1880946',
                    currentAdjPrice: '53.78',
                    futures: null,
                    basis: '53.78',
                    deferPayDate: '2020-03-19 13:17:25.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-03-19 13:15:00.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1880945',
                    currentAdjPrice: '51.26',
                    futures: null,
                    basis: '51.26',
                    deferPayDate: '2020-03-19 13:15:00.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '150.0',
                    date: '2020-03-19 13:15:00.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1880945',
                    currentAdjPrice: '253.72',
                    futures: '202.46',
                    basis: '51.26',
                    deferPayDate: '2020-03-19 13:15:00.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-03 08:09:56.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1875105',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-03 08:09:56.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '700.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-03 08:12:44.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1875106',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-03 08:12:44.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '700.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-03 08:09:56.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1875105',
                    currentAdjPrice: '216.87',
                    futures: '216.87',
                    basis: null,
                    deferPayDate: '2020-02-03 08:09:56.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '100.0',
                    date: '2020-02-03 08:09:56.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1875105',
                    currentAdjPrice: '257.2',
                    futures: '216.87',
                    basis: '40.33',
                    deferPayDate: '2020-02-03 08:09:56.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '100.0',
                    date: '2020-02-03 08:12:44.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1875106',
                    currentAdjPrice: '40.33',
                    futures: null,
                    basis: '40.33',
                    deferPayDate: '2020-02-03 08:12:44.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'RED SPRING WHEAT'
          }
        ],
        accountNumber: '1177174'
      },
      {
        accountName: 'Shee Wee Farms Inc',
        commodities: [
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '84.0',
                    date: '2020-07-14 13:19:14.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1898732',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-07-14 13:19:14.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '294.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '42.0',
                    date: '2020-08-31 13:01:19.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1905708',
                    currentAdjPrice: '500.0',
                    futures: '500.0',
                    basis: null,
                    deferPayDate: '2020-08-31 13:01:19.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '210.0',
                    currentValue: '-'
                  }
                ],
                cropYear: '2021-2022',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CANOLA'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '150.0',
                    date: '2020-06-24 14:15:31.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1895881',
                    currentAdjPrice: '229.67',
                    futures: '0.0',
                    basis: '229.67',
                    deferPayDate: '2020-06-24 14:15:31.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'NB METCALFE DES BARLEY'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-05 16:31:38.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1875510',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-05 16:31:38.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '1400.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-05 16:39:49.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1875516',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-05 16:39:49.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '1400.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-05 16:47:48.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1875519',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-05 16:47:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '1400.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-05 16:51:01.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1875520',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-05 16:51:01.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '1400.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-05 16:31:38.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1875510',
                    currentAdjPrice: '46.18',
                    futures: null,
                    basis: '46.18',
                    deferPayDate: '2020-02-05 16:31:38.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2020-02-05 16:39:49.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1875516',
                    currentAdjPrice: '53.78',
                    futures: null,
                    basis: '53.78',
                    deferPayDate: '2020-02-05 16:39:49.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2020-02-05 16:47:48.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1875519',
                    currentAdjPrice: '43.72',
                    futures: null,
                    basis: '43.72',
                    deferPayDate: '2020-02-05 16:47:48.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2020-02-05 16:51:01.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1875520',
                    currentAdjPrice: '48.28',
                    futures: null,
                    basis: '48.28',
                    deferPayDate: '2020-02-05 16:51:01.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2020-02-05 16:31:38.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1875510',
                    currentAdjPrice: '263.05',
                    futures: '216.87',
                    basis: '46.18',
                    deferPayDate: '2020-02-05 16:31:38.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-04-07 14:02:21.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1885247',
                    currentAdjPrice: '49.25',
                    futures: null,
                    basis: '49.25',
                    deferPayDate: '2020-04-07 14:02:21.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-04-07 17:59:56.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1885395',
                    currentAdjPrice: '49.25',
                    futures: null,
                    basis: '49.25',
                    deferPayDate: '2020-04-07 17:59:56.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '225.0',
                    date: '2020-04-07 14:02:21.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1885247',
                    currentAdjPrice: '236.37',
                    futures: '187.12',
                    basis: '49.25',
                    deferPayDate: '2020-04-07 14:02:21.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '225.0',
                    date: '2020-04-07 17:59:56.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1885395',
                    currentAdjPrice: '236.37',
                    futures: '187.12',
                    basis: '49.25',
                    deferPayDate: '2020-04-07 17:59:56.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '225.0',
                    date: '2020-09-30 08:54:43.0',
                    deliveryPoint: 'Edmonton AB Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1911386',
                    currentAdjPrice: '236.37',
                    futures: '187.12',
                    basis: '49.25',
                    deferPayDate: '2020-09-30 08:54:43.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '331.52',
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'RED SPRING WHEAT'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '84.0',
                    date: '2020-06-25 18:42:33.0',
                    deliveryPoint: 'AB I17 PREM Devon O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1896098',
                    currentAdjPrice: '490.0',
                    futures: '490.0',
                    basis: null,
                    deferPayDate: '2020-06-25 18:42:33.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '42.0',
                    date: '2020-07-08 14:15:41.0',
                    deliveryPoint: 'AB I17 PREM Devon O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1897643',
                    currentAdjPrice: '492.0',
                    futures: '492.0',
                    basis: null,
                    deferPayDate: '2020-07-08 14:15:41.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '42.0',
                    date: '2020-07-09 14:15:55.0',
                    deliveryPoint: 'AB I17 PREM Devon O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1897995',
                    currentAdjPrice: '495.0',
                    futures: '495.0',
                    basis: null,
                    deferPayDate: '2020-07-09 14:15:55.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '70.0',
                    date: '2020-07-14 12:21:42.0',
                    deliveryPoint: 'AB I17 PREM Devon O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1898713',
                    currentAdjPrice: '492.3',
                    futures: '492.3',
                    basis: null,
                    deferPayDate: '2020-07-14 12:21:42.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '84.0',
                    date: '2020-05-12 14:15:34.0',
                    deliveryPoint: 'AB I17 PREM Devon O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1889708',
                    currentAdjPrice: '490.0',
                    futures: '490.0',
                    basis: null,
                    deferPayDate: '2020-05-12 14:15:34.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CSCO CANOLA'
          }
        ],
        accountNumber: '1229052'
      },
      {
        accountName: 'I and C Farms and Son Ltd',
        commodities: [
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2020-07-10 12:31:08.0',
                    deliveryPoint: '431-St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1898306',
                    currentAdjPrice: '468.9',
                    futures: '496.9',
                    basis: '-28.0',
                    deferPayDate: '2020-07-10 12:31:08.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2020-07-10 12:35:15.0',
                    deliveryPoint: '431-St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1898310',
                    currentAdjPrice: '466.2',
                    futures: '495.2',
                    basis: '-29.0',
                    deferPayDate: '2020-07-10 12:35:15.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '794.0',
                    date: '2020-09-21 11:55:29.0',
                    deliveryPoint: '431-St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1909852',
                    currentAdjPrice: '505.9',
                    futures: '539.9',
                    basis: '-34.0',
                    deferPayDate: '2020-09-21 11:55:29.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '453.0',
                    date: '2020-06-19 12:17:11.0',
                    deliveryPoint: '431-St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1895078',
                    currentAdjPrice: '456.1',
                    futures: '484.1',
                    basis: '-28.0',
                    deferPayDate: '2020-06-19 12:17:11.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-03-10 12:18:36.0',
                    deliveryPoint: '431-St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1878935',
                    currentAdjPrice: '-35.0',
                    futures: null,
                    basis: '-35.0',
                    deferPayDate: '2020-03-10 12:18:36.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '160.0',
                    date: '2020-03-10 12:18:36.0',
                    deliveryPoint: '431-St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1878935',
                    currentAdjPrice: '440.0',
                    futures: '475.0',
                    basis: '-35.0',
                    deferPayDate: '2020-03-10 12:18:36.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CRUSH CANOLA'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '544.0',
                    date: '2020-09-30 14:16:00.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1911525',
                    currentAdjPrice: '229.65',
                    futures: '0.0',
                    basis: '229.65',
                    deferPayDate: '2020-09-30 14:16:00.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '871.0',
                    date: '2020-10-14 19:00:55.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1914225',
                    currentAdjPrice: '241.13',
                    futures: '0.0',
                    basis: '241.13',
                    deferPayDate: '2020-10-14 19:00:55.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'NB COPELAND DES BARLEY'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '120.0',
                    date: '2020-09-11 14:15:43.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1907948',
                    currentAdjPrice: '505.0',
                    futures: '505.0',
                    basis: null,
                    deferPayDate: '2020-09-11 14:15:43.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2021-2022',
                gpoContracts: null,
                prodcontracts: null
              },
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '336.0',
                    date: '2020-09-21 11:56:40.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1909854',
                    currentAdjPrice: '545.6',
                    futures: '545.6',
                    basis: null,
                    deferPayDate: '2020-09-21 11:56:40.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-09-04 11:48:38.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1906608',
                    currentAdjPrice: '514.9',
                    futures: '514.9',
                    basis: null,
                    deferPayDate: '2020-09-04 11:48:38.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '271.548',
                    date: '2020-09-04 11:48:38.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1906608',
                    currentAdjPrice: '536.9',
                    futures: '514.9',
                    basis: '22.0',
                    deferPayDate: '2020-09-04 11:48:38.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-08-27 09:31:04.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1904915',
                    currentAdjPrice: '508.9',
                    futures: '508.9',
                    basis: null,
                    deferPayDate: '2020-08-27 09:31:04.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '208.028',
                    date: '2020-08-27 09:31:04.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1904915',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-08-27 09:31:04.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-06-19 14:10:31.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1895173',
                    currentAdjPrice: '10.0',
                    futures: null,
                    basis: '10.0',
                    deferPayDate: '2020-06-19 14:10:31.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2020-06-22 14:15:35.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1895556',
                    currentAdjPrice: '485.0',
                    futures: '485.0',
                    basis: null,
                    deferPayDate: '2020-06-22 14:15:35.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2020-06-19 14:10:31.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1895173',
                    currentAdjPrice: '495.0',
                    futures: '485.0',
                    basis: '10.0',
                    deferPayDate: '2020-06-19 14:10:31.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '300.0',
                    date: '2020-06-19 14:10:31.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1895173',
                    currentAdjPrice: '495.0',
                    futures: '485.0',
                    basis: '10.0',
                    deferPayDate: '2020-06-19 14:10:31.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-07-08 10:24:07.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1897547',
                    currentAdjPrice: '485.8',
                    futures: '485.8',
                    basis: null,
                    deferPayDate: '2020-07-08 10:24:07.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-07-08 10:25:56.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1897548',
                    currentAdjPrice: '485.6',
                    futures: '485.6',
                    basis: null,
                    deferPayDate: '2020-07-08 10:25:56.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '266.0',
                    date: '2020-07-08 10:24:07.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1897547',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-07-08 10:24:07.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '188.388',
                    date: '2020-07-08 10:25:56.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1897548',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-07-08 10:25:56.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2019-10-22 14:15:33.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1861485',
                    currentAdjPrice: '485.0',
                    futures: '485.0',
                    basis: null,
                    deferPayDate: '2019-10-22 14:15:33.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2019-10-22 14:15:33.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1861485',
                    currentAdjPrice: '485.0',
                    futures: '485.0',
                    basis: '0.0',
                    deferPayDate: '2019-10-22 14:15:33.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '355.8',
                    date: '2019-11-20 10:17:37.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1865202',
                    currentAdjPrice: '490.0',
                    futures: '490.0',
                    basis: '0.0',
                    deferPayDate: '2019-11-20 10:17:37.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '200.0',
                    date: '2019-12-20 14:15:34.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Hedge To Arrive',
                    contractNumber: '1869970',
                    currentAdjPrice: '495.0',
                    futures: '495.0',
                    basis: null,
                    deferPayDate: '2019-12-20 14:15:34.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-10 13:20:39.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1876053',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: '0.0',
                    deferPayDate: '2020-02-10 13:20:39.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '25.408',
                    date: '2020-02-10 13:20:39.0',
                    deliveryPoint: '431-PREM St Louis SK O/F',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1876053',
                    currentAdjPrice: '475.0',
                    futures: '475.0',
                    basis: '0.0',
                    deferPayDate: '2020-02-10 13:20:39.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'CSCO CANOLA'
          },
          {
            cropYears: [
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '126.0',
                    date: '2020-10-14 14:00:20.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1914128',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-10-14 14:00:20.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '882.0',
                    currentValue: '-'
                  }
                ],
                cropYear: '2021-2022',
                gpoContracts: null,
                prodcontracts: null
              },
              {
                merchContracts: [
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-02-03 13:45:57.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Deferred Price Limited',
                    contractNumber: '1875171',
                    currentAdjPrice: '0.0',
                    futures: null,
                    basis: null,
                    deferPayDate: '2020-02-03 13:45:57.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: '882.0',
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '126.0',
                    date: '2020-02-03 13:45:57.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1875171',
                    currentAdjPrice: '45.02',
                    futures: null,
                    basis: '45.02',
                    deferPayDate: '2020-02-03 13:45:57.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-03-20 09:57:46.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1881351',
                    currentAdjPrice: '51.48',
                    futures: null,
                    basis: '51.48',
                    deferPayDate: '2020-03-20 09:57:46.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '252.0',
                    date: '2020-03-20 09:57:46.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1881351',
                    currentAdjPrice: '257.21',
                    futures: '205.73',
                    basis: '51.48',
                    deferPayDate: '2020-03-20 09:57:46.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '0.0',
                    date: '2020-03-20 09:54:24.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Basis',
                    contractNumber: '1881341',
                    currentAdjPrice: '46.99',
                    futures: null,
                    basis: '46.99',
                    deferPayDate: '2020-03-20 09:54:24.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  },
                  {
                    quantityToBeDelivered: '252.0',
                    date: '2020-03-20 09:54:24.0',
                    deliveryPoint: 'Clavet SK Dlvd',
                    pricingLotInfo: null,
                    product: '-',
                    originalQuantity: '0.0',
                    contractPriceType: 'Priced',
                    contractNumber: '1881341',
                    currentAdjPrice: '247.8',
                    futures: '200.81',
                    basis: '46.99',
                    deferPayDate: '2020-03-20 09:54:24.0',
                    shipmentPeriod: null,
                    futuresMonth: null,
                    adjust: null,
                    currentValue: '-'
                  }
                ],
                cropYear: '2020-2021',
                gpoContracts: null,
                prodcontracts: null
              }
            ],
            commodityName: 'RED SPRING WHEAT'
          }
        ],
        accountNumber: '1223040'
      }
    ]
  };
  contractsReport.handlerData(jsonData);
};
